clientside/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name='clientside'

urlpatterns = [
    path('', views.Home, name = 'homepage'),
    path('about/', views.About, name = 'about'),
    path('services/', views.Services, name = 'services'),
    path('track/', views.Track, name = 'track'),
    path('contact/', views.Contact, name = 'contact'),  
    path('get-a-quote/', views.Quote, name = 'get-a-quote'),  

    
]
urlpatterns += staticfiles_urlpatterns()

dispatch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientside.urls')),
    path('adminside/', include('adminside.urls')),
]

clientside/models.py
from django.db import models
import uuid

# Create your models here.

class Client(models.Model):
    sender_name = models.CharField(max_length=50)
    sender_email = models.EmailField()
    subject = models.CharField(max_length = 50)
    message = models.CharField(max_length = 200)
    
    def __str__(self):
        return self.sender_name
    
class Quote(models.Model):
    departure = models.CharField(max_length= 50, null = True)
    delivery = models.CharField(max_length= 50, null = True)
    weight = models.CharField(max_length= 50, null = True)
    dimensions = models.CharField(max_length= 50, null = True)
    name = models.CharField(max_length=50, null = True)
    email = models.EmailField( null = True)
    phone = models.CharField(max_length = 50, null = True)
    message = models.TextField(max_length = 200, null = True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable= False)
    
    def __str__(self):
        return self.name
    

clientside/forms.py
from django.forms import ModelForm
from .models import Quote
        
class Messageform(ModelForm):
    class Meta:
        model = Quote
        fields = '__all__'
        
class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = '__all__'

clientside/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from adminside.models import Order
from django.contrib import messages
from .models import Client
from . forms import QuoteForm

# Create your views here.

def Home(request):
    return render(request, 'home.html')

def About(request):
    return render(request, 'about.html')

def Services(request):
    return render(request, 'services.html')

def Track(request):
    if request.method == 'POST':
        tracking_number = request.POST.get('tracking_number')
        try:
            model_instance = Order.objects.get(tracking_number=tracking_number)
            return render(request, 'track.html', {'model_instance': model_instance})
        except Order.DoesNotExist:
            messages.error(request, 'Order not found.')
    return render(request, 'track.html')


def Contact(request):
    form = QuoteForm()
    if request.method =='POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ClientSide:contact')
    context = {'form':form}
    return render(request, 'contact.html',context )

def details(request, pk):
    order = Order.objects.get(id=pk)
    return render(request, 'details.html', {'order': order})

def deleteorder(request, pk):
    order = Order.objects.get(id=pk)
    if request.method =='POST':
        order.delete()
        return redirect('AdminSide:order-list')
    context = {'order': order}
    return render(request, 'delete.html', context)

def Quote(request):
    form = QuoteForm()
    if request.method =='POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ClientSide:get-a-quote')
    context = {'form':form }
    return render(request, 'get-a-quote.html')

clientside/templates/about.html
{% extends 'basic.html'%}
{% load static %}
{% block content %}
{% block about_active %} active {% endblock %}

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
        <div class="page-header d-flex align-items-center" style="background-image: url('assets/img/page-header.jpg');">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                <h2>About</h2>
                <p>we envision a world where connections are empowered and logistics is redefined. Our vision is to revolutionize the way packages are delivered, creating a seamless and transformative experience for individuals and businesses alike.</p>
              </div>
            </div>
          </div>
        </div>
        <nav>
          <div class="container">
            <ol>
              <li><a href="{% url 'clientside:homepage' %}">Home</a></li>
              <li>About</li>
            </ol>
          </div>
        </nav>
      </div><!-- End Breadcrumbs -->
  
      <!-- ======= About Us Section ======= -->
      <section id="about" class="about">
        <div class="container" data-aos="fade-up">
  
          <div class="row gy-4">
            <div class="col-lg-6 position-relative align-self-start order-lg-last order-first">
              <img src="assets/img/about.jpg" class="img-fluid" alt="">
              <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
            </div>
            <div class="col-lg-6 content order-last  order-lg-first">
              <h3>About Us</h3>
              <p>
               Turbo Transit Logistics is a leading logistics company dedicated to providing efficient and reliable shipping and transportation solutions. With years of industry experience, we have built a reputation for excellence, customer satisfaction, and a commitment to meeting the diverse needs of our clients.

              </p>
              <ul>
                <li data-aos="fade-up" data-aos-delay="100">
                  <i class="bi bi-diagram-3"></i>
                  <div>
                    <h5>Transparency and open communication</h5>
                    <p>Are fundamental values for us. We believe in building strong and collaborative relationships with our clients, based on trust, integrity, and mutual success</p>
                  </div>
                </li>
                <li data-aos="fade-up" data-aos-delay="200">
                  <i class="bi bi-fullscreen-exit"></i>
                  <div>
                    <h5>We are committed to delivering exceptional service</h5>
                    <p>We optimize your operations, and exceed your expectations at every step</p>
                  </div>
                </li>
                <li data-aos="fade-up" data-aos-delay="300">
                  <i class="bi bi-broadcast"></i>
                  <div>
                    <h5>Experience reliability and efficiency</h5>
                    <p>Contact us today to discuss how we can support your logistics requirements and contribute to the success of your business.</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
  
        </div>
      </section><!-- End About Us Section -->
 
      <section id="service" class="services pt-0">
        <div class="container" data-aos="fade-up">
  
          <div class="section-header">
            <span>Our Vision</span>
            <h2>Our Vision</h2>
  
          </div>
  
          <div class="row gy-4">
  
            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
              <div class="card">
              
                <h3><a href="{% url 'clientside:services' %}" class="stretched-link">Enabling Growth and Prosperity</a></h3>
                <p> We understand the vital role that logistics plays in the success of businesses. Our vision is to empower businesses by providing efficient and reliable delivery solutions. By seamlessly transporting products, streamlining supply chains, and offering value-added services, we aim to contribute to the growth and prosperity of our clients.
                </p>
              </div>
            </div><!-- End Card Item -->
  
            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="200">
              <div class="card">
                <h3><a href="{% url 'clientside:services' %}" class="stretched-link">Connecting People and Communities</a></h3>
                <p> We believe that every package carries more than just physical goods—it carries emotions, aspirations, and connections. Our vision is to bridge distances, connecting people and communities across the globe. Whether it's reuniting loved ones, enabling businesses to thrive, or supporting humanitarian efforts, we aim to be the catalyst that brings people closer together.
                </p>
              </div>
            </div><!-- End Card Item -->
  
            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="300">
              <div class="card">
                
                <h3><a href="{% url 'clientside:services' %}" class="stretched-link">Embracing Innovation and Technology</a></h3>
                <p>We believe in the power of innovation and technology to transform the logistics industry. Our vision is to stay at the forefront of technological advancements, leveraging cutting-edge solutions to enhance the efficiency, transparency, and sustainability of our operations. By embracing innovation, we aim to continuously improve our services and exceed customer expectations.
                </p>
              </div>
            </div><!-- End Card Item -->
  
            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="400">
              <div class="card">
                <h3><a href="{% url 'clientside:services' %}" class="stretched-link">Championing Sustainability and Responsibility</a></h3>
                <p>We recognize our responsibility to protect the planet and future generations. Our vision is to lead the industry in sustainable practices, reducing our environmental impact and promoting responsible logistics. Through eco-friendly initiatives, carbon footprint reduction, and partnerships with like-minded organizations, we aim to create a greener and more sustainable future.
                </p>
              </div>
            </div><!-- End Card Item -->
  
            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="500">
              <div class="card">
                
                <h3><a href="{% url 'clientside:services' %}" class="stretched-link">Delivering Excellence and Delight</a></h3>
                <p>Our vision is to set the standard of excellence in the courier industry. We strive to deliver beyond expectations, providing exceptional customer service, reliable deliveries, and innovative solutions. Our goal is to delight our customers at every touchpoint, earning their trust and loyalty as their preferred courier partner.
                </p>
              </div>
            </div><!-- End Card Item -->
  
            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="600">
              <div class="card">
                
                <h3><a href="{% url 'clientside:services' %}" class="stretched-link">Empowering our Team</a></h3>
                <p>We believe that our success lies in the hands of our dedicated team. Our vision is to foster a supportive and inclusive work environment that values collaboration, personal growth, and professional development. By empowering our team members, we aim to cultivate a passionate and motivated workforce dedicated to delivering excellence.
                </p>
              </div>
            </div><!-- End Card Item -->
  
          </div>
  
        </div>
      </section>
      <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <span>Frequently Asked Questions</span>
          <h2>Frequently Asked Questions</h2>

        </div>

        <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="200">
          <div class="col-lg-10">

            <div class="accordion accordion-flush" id="faqlist">

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-1">
                    <i class="bi bi-question-circle question-icon"></i>
                    Can I ship items of any size internationally?
                  </button>
                </h3>
                <div id="faq-content-1" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                    While most items can be shipped internationally, there may be restrictions on certain sizes, weights, or types of goods imposed by carriers or customs regulations. It is important to check the specific regulations and requirements of the destination country. Our team can assist you in determining any size or weight restrictions and provide guidance on shipping options for your specific items.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-2">
                    <i class="bi bi-question-circle question-icon"></i>
                    Do you provide insurance for international shipments?
                  </button>
                </h3>
                <div id="faq-content-2" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                    Yes, we offer insurance options for international shipments to provide added protection. Our insurance coverage safeguards your packages against loss, damage, or theft during transit. It is recommended to consider insurance for valuable or fragile items. Our team can provide information on insurance options and help you choose the coverage that best suits your needs.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-3">
                    <i class="bi bi-question-circle question-icon"></i>
                    Is tracking available for international shipments?
                  </button>
                </h3>
                <div id="faq-content-3" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                    Yes, we offer tracking services for international shipments. Once your package is in transit, you can easily track its progress online through our tracking system. You will receive a tracking number that allows you to monitor the shipment's journey, view real-time updates, and stay informed about its estimated delivery date.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-4">
                    <i class="bi bi-question-circle question-icon"></i>
                    How long does international shipping typically take?
                  </button>
                </h3>
                <div id="faq-content-4" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                    <i class="bi bi-question-circle question-icon"></i>
                    The duration of international shipping depends on various factors such as the destination, shipping method chosen, customs clearance, and any unforeseen circumstances. Generally, international shipments can range from a few days to several weeks. We provide estimated delivery times based on the destination and selected shipping service to give you a better idea of the timeframe.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-5">
                    <i class="bi bi-question-circle question-icon"></i>
                    What documents are required for international shipping?
                  </button>
                </h3>
                <div id="faq-content-5" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                    The specific documents required may vary depending on the destination and the nature of the shipment. However, common documents include a commercial invoice, packing list, and any necessary permits or licenses. Our team will guide you through the documentation process and ensure that all required paperwork is properly prepared.
                  </div>
                </div>
              </div><!-- # Faq item-->

            </div>

          </div>
        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->

  
{% endblock %}

clientside/templates/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title></title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/logo1.png' %}" rel="icon">
  <!-- <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon"> -->

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->

  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">


  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/main2.css' %}" rel="stylesheet">

</head>

<script src="//code.tidio.co/jooevtetykasxvmsis1pjvmskqre7ob8.js" async></script>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top bg-dark">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="#" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <img src="{% static 'assets/img/logo1.png' %}" alt="">
        <h1 class="sitename">Turbo Transit logistics</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a class="{% block homepage_active %}{% endblock %}" href="{% url 'clientside:homepage' %}">Home<br></a></li>
          <li><a class="{% block about_active %}{% endblock %}" href="{% url 'clientside:about' %}">About</a></li>
          <li><a class="{% block services_active %}{% endblock %}" href="{% url 'clientside:services' %}">Services</a></li>
          <li><a class="{% block track_and_trace_active %}{% endblock %}" href="{% url 'clientside:track' %}">Track and Trace</a></li>
          <li><a class="{% block contact_active %}{% endblock %}" href="{% url 'clientside:contact' %}">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>

  <main class="main">

   {% block hero %}
   {% endblock %}

   {% block content %}
   {% endblock %}

    

  </main>

 <!-- ======= Footer ======= -->
 <footer id="footer" class="footer">

  <div class="container">
    <div class="row gy-4">
      <div class="col-lg-5 col-md-12 footer-info">
        <a href="" class="logo d-flex align-items-center">
          <span>Turbo Transit Logistics</span>
        </a>
        <p>Experience the speed, efficiency, and reliability of Turbo Transit Logistics. Contact us today and let us take care of your logistics needs, so you can stay ahead in an ever-evolving business landscape.</p>
        <div class="social-links d-flex mt-4">
          <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
          <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
          <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
          <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
      </div>

      <div class="col-lg-2 col-6 footer-links">
        <h4>Useful Links</h4>
        <ul>
          <li><a href="{% url 'clientside:homepage' %}">Home</a></li>
          <li><a href="{% url 'clientside:about' %}">About us</a></li>
          <li><a href="{% url 'clientside:services' %}">Services</a></li>
          <li><a href="#">Terms of service</a></li>
          <li><a href="#">Privacy policy</a></li>
        </ul>
      </div>

      <div class="col-lg-2 col-6 footer-links">
        <h4>Our Services</h4>
        <ul>
          <li><a href="{% url 'clientside:services' %}">Storage</a></li>
          <li><a href="{% url 'clientside:services' %}">Logistics</a></li>
          <li><a href="{% url 'clientside:services' %}">Warehousing</a></li>
          <li><a href="{% url 'clientside:services' %}">Trucking</a></li>
          <li><a href="{% url 'clientside:services' %}">Packaging</a></li>
        </ul>
      </div> 

      <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
        <h4>Contact Us</h4>
        <p>
          2050 Cessna <br>
          Florida<br>
          United States <br><br>
          <strong>Phone:</strong> +1 561 293 3780<br>
          <strong>Email:</strong>logisticturbotransit@gmail.com<br>
        </p>

      </div>

    </div>
  </div>

  <div class="container mt-4">
    <div class="copyright">
      &copy; Copyright <strong><span>Turbo Transit Logistics</span></strong>. All Rights Reserved
    </div>
  </div>

</footer><!-- End Footer -->
<!-- End Footer -->

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/main2.js' %}"></script>


</body>

</html>

clientside/templates/contact.html
{% extends 'basic.html' %}
{% load static %}
{% block contact_active %} active {% endblock %}

{% block content %}
 <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="page-header d-flex align-items-center" style="background-image: url('assets/img/page-header.jpg');">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-6 text-center">
            <h2>Contact</h2>
            <p>Our dedicated team of logistics experts is ready to assist you in finding the best solutions for your shipping and transportation needs. We understand that each customer is unique, and we pride ourselves on delivering personalized support tailored to your specific requirements.</p>
          </div>
        </div>
      </div>
    </div>
    <nav>
      <div class="container">
        <ol>
          <li><a href="{% url 'clientside:homepage'%}">Home</a></li>
          <li>Contact</li>
        </ol>
      </div>
    </nav>
  </div><!-- End Breadcrumbs -->

  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container" data-aos="fade-up">

      <div>
       <!-- <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3390.1085984584006!2d-102.3983782243763!3d31.82203547407729!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86fbca330bc4e5b7%3A0xc272881b6abd499e!2s2612%20Maurice%20Rd%2C%20Odessa%2C%20TX%2079763%2C%20USA!5e0!3m2!1sen!2scm!4v1708295948350!5m2!1sen!2scm" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> -->
      </div><!-- End Google Maps -->

      <div class="row gy-4 mt-4">

        <div class="col-lg-4">

          <div class="info-item d-flex">
            <i class="bi bi-geo-alt flex-shrink-0"></i>
            <div>
              <h4>Location:</h4>
              <p> 2050 Cessna <br>
                Florida<br> United States</p>
            </div>
          </div><!-- End Info Item -->

          <div class="info-item d-flex">
            <i class="bi bi-envelope flex-shrink-0"></i>
            <div>
              <h4>Email:</h4>
              <p>logisticsturbotransit@gmail.com</p>
            </div>
          </div><!-- End Info Item -->

          <div class="info-item d-flex">
            <i class="bi bi-phone flex-shrink-0"></i>
            <div>
              <h4>Call:</h4>
              <p> +1 561 293 3780</p>
            </div>
          </div><!-- End Info Item -->

        </div>

        <div class="col-lg-8">
          <form action="" method="POST" role="form" class="">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 form-group">
                <input type="text" name="sender_name" class="form-control" id="name" placeholder="Your Name" required>
              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <input type="email" class="form-control" name="sender_email" id="email" placeholder="Your Email" required>
              </div>
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
            </div>
            <div class="form-group mt-3">
              <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
            </div>
            <div class="my-3">
              <!-- <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div> -->
            </div>
            <div class="text-center success"><button type="submit">Send Message</button></div>
          </form>
        </div><!-- End Contact Form -->

      </div>

    </div>
 
{% endblock %}