adminside/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name='AdminSide'

urlpatterns = [
    path('', views.loginUser, name='login'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('order-list/',views.OrderList, name='order-list'),
    path('new-order/',views.NewOrder, name='new-order'),
    path('update-order/<str:pk>/',views.updateOrder, name='update-order'),
    path('details/<str:pk>/', views.details, name = 'details'),
    path('delete/<str:pk>/', views.deleteorder, name='delete-order'),
   
    path('alllmessages/',views.Allmessages, name='all-messages'),
    path('message-details/<str:pk>/', views.messageDetails, name = 'message-details'),
    path('delete/<str:pk>/', views.deletemessage, name='delete-message'),
    path('test/', views.status, name ='email')
    
]
urlpatterns += staticfiles_urlpatterns()

dispatch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientside.urls')),
    path('adminside/', include('adminside.urls')),
]

adminside/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

ORDERSTATUS = ((1, "Pending"),
               (2, "Picked up"),
               (3, "On hold"),
               (4, "Out for delivery"),
               (5, "In Transit"),
               (6, "Enroute"),
               (7, "Cancelled"),
               (8, "Delivered"),
               (9, "Returned"),
               (10, "Intercepted by DEA"),
               (11, "Held by Customs"))

class user (models.Model):
    username = models.CharField(max_length=10)
    password = models.CharField(max_length=10)
    
    def __str__(self):
        return self.username
    
class Order(models.Model):
    # sender information
    sender_name = models.CharField(max_length=50)
    sender_address = models.CharField(max_length=50)
    sender_email = models.EmailField()
    sender_phone = models.CharField(null=True, blank=True, max_length=50)
    
    
    # Recievers information
    reciever_name = models.CharField(max_length=50, null=True, blank=True)
    Phone_number = models.CharField(null=True, blank=True, max_length=50)
    reciever_address = models.CharField(max_length=50, null=True, blank=True)
    reciever_email = models.EmailField()
   
    
    # Order information
    origin = models.CharField(max_length=50, null=True, blank=True)
    destination = models.CharField(max_length=50, null=True, blank=True)
    package = models.IntegerField(null=True)
    carrier = models.CharField(max_length=50, null=True, blank=True)
    type_of_shipment = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    reference_number = models.CharField(max_length=50, null=True, blank=True)
    weight = models.CharField(max_length=50, null=True, blank=True)
    departure_date = models.DateField(null=True, blank=True)
    arrival_date = models.DateField(null=True, blank=True)
    departure_time = models.CharField(null=True, blank=True, max_length=10)
    arrival_time = models.CharField(null=True, blank=True,  max_length=10)
    payment_method = models.CharField(max_length=50, null=True, blank=True)  
    tracking_number = models.CharField(default=f"EXWA{str(uuid.uuid4())[:18]}-ORDER", max_length=30, unique=True)
    status = models.IntegerField(choices=ORDERSTATUS, default=1)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable= False)
    date_added = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_added']
        
        
    def __str__(self):
        return f"Order {self.id} - {self.get_status_display()}"
        
        
    def generate_tracking_number(self):
        uuid_string = str(uuid.uuid4().int)
        formatted_uuid = f"EXWA{str(uuid.uuid4())[:18]}-ORDER"
        return formatted_uuid

    def save(self, *args, **kwargs):
        if not self.tracking_number:
            self.tracking_number = self.generate_tracking_number()
        super().save(*args, **kwargs)
       
    

    

adminside/forms.py
from django.forms import ModelForm
from .models import Order, user



class Orderform(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        
        
class Userform(ModelForm):
    class Meta:
        model = user
        fields = '__all__'

adminside/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.core.mail import send_mail
from django.contrib.auth.models import User
from .forms import Orderform, Userform
from . models import Order
from clientside.models import Quote
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.core.mail import EmailMessage
from django.template.loader import render_to_string

# Create your views here.

@login_required
def Dashboard(request):
    count =Order.objects.count()
    return render(request, 'index.html', {'count':count} )

# def logoutUser(request):
#     logout(request)
#     return redirect('panel_admin:login')


def loginUser(request):
    msg = None
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'username does not exist')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('AdminSide:dashboard')   
        else:
            messages.error(request, 'Username or password is not correct.')
    return render(request, 'login.html')


def NewOrder(request):
    form = Orderform()  
    if request.method =='POST':
        form = Orderform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('AdminSide:order-list')
    context = {'form':form}
    return render(request, 'newOrder.html',context )

def updateOrder(request, pk):
    order = Order.objects.get(id=pk)
    form = Orderform(instance=order)
    
    if request.method == 'POST':
        form = Orderform(request.POST, instance=order)
        
        if form.is_valid():
            form.save()

            # Determine the status of the order
            status = order.status  

            # Select email template based on status
            if status in ['Processed', 'Dispatch', 'En Route', 'Delivered']:
                email_template = 'email_template.html'  # Change this to the appropriate email template for each status

                # Render email template with order details
                email_context = {'order': order}
                email_content = render_to_string(email_template, email_context)

                # Send HTML email
                email_subject = 'Order status updated'
                sender_email = 'Tzuarg@gmail.com'  # Update with your email
                recipient_email = order.email  # Assuming 'email' is a field in your Order model
                email = EmailMessage(email_subject, email_content, sender_email, [recipient_email])
                email.content_subtype = 'html'
                email.send()

            return redirect('AdminSide:order-list')
    
    context = {'form': form}
    return render(request, 'newOrder.html', context)


def OrderList(request):
    orders = Order.objects.all()
    return render(request, 'orderList.html', {'orders': orders})

def details(request, pk):
    order = Order.objects.get(id=pk)
    return render(request, 'details.html', {'order': order})

def deleteorder(request, pk):
    order = Order.objects.get(id=pk)
    if request.method =='POST':
        order.delete()
        return redirect('AdminSide:order-list')
    context = {'order': order}
    return render(request, 'delete.html', context)

  
def Allmessages(request):
    messages = Quote.objects.all()
    return render(request, 'allmessages.html', {'messages': messages})

def messageDetails(request, pk):
    messages = Quote.objects.get(id=pk)
    return render(request, 'messageDetail.html', {'messages':messages})

def deletemessage(request, pk):
    message = Quote.objects.get(id=pk)
    if request.method =='POST':
        message.delete()
        return redirect('AdminSide:allmessages')
    context = {'message': message}
    return render(request, 'delete.html', context)


def status(request):
    return render(request, 'email_template.html')

adminside/templates/allmessages.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <table class="table table-bordered border-primary">
        <thead>
          <tr>    
            <th scope="col">#</th>
            <th scope="col">Client name</th>
            <th scope="col">Email</th>
            <th scope="col">subject</th>
            <th scope="col">action</th>
          </tr>
        </thead>
        <tbody>
          {% for messages in messages %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{messages.name}}</td>
            <td>{{messages.email|truncatechars:20}} ...</td>
            <td>{{messages.subject| truncatechars:10}}</td>
            <td>
              <a href="{% url 'AdminSide:message-details' messages.id %}"><i class="fa-solid fa-eye"></i>view</a>

              <a href=""><i class="fas fa-trash-alt"></i>delete</a>     
            </td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
    </div>
  </div>
  
  

{% endblock %}

adminside/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>NiceAdmin Panel</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/quill/quill.snow.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/quill/quill.bubble.css' %}">
  <link href="{%static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  {% block css %}

  {% endblock %}

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: Nov 17 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">NiceAdmin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href="{% url 'AdminSide:all-messages'%}"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="dropdown-footer">
              <a href="{% url 'AdminSide:all-messages'%}">Show all messages</a>
            </li>

          </ul><!-- End Messages Dropdown Items -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.username}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{request.user.username}}</h6>
              <span>Tracking courier</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'AdminSide:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'AdminSide:new-order' %}">
          <i class="bi bi-grid"></i>
          <span>Add new Order</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'AdminSide:order-list' %}">
          <i class="bi bi-grid"></i>
          <span>View all Orders</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'AdminSide:all-messages' %}">
          <i class="bi bi-grid"></i>
          <span>View all messages</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'AdminSide:email' %}">
          <i class="bi bi-grid"></i>
          <span>View emails</span>
        </a>
      </li>
      <li class="nav-heading">Pages</li>
    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">
    {% block content %}

    {% endblock %}

  </main><!-- End #main -->

  

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->

  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>


  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

adminside/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container  shadow p-3 mb-5 rounded">
    <a href="{% url 'AdminSide:order-list'%}"><button type="button" class="btn-secondary"> << back </button></a>
      <div class="nav navbar border">
          <div class="row">
              <div class="title"><h5><small>Client name: </small>{{ order.reciever_name}}</h5></div>
              <div class="timestamp">created on: {{order.date_added}}</div>
          </div>
      </div>
      <div class="sender">
          <h5 class="text-center">sender's information</h5>
          <table class="table">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">email</th>
                  <th scope="col">address</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{order.sender_name}}</td>
                  <td>{{order.sender_email}}</td>
                  <td>{{order.sender_address}}</td>
                </tr>
              </tbody>
            </table>
      </div>
      <div class="container-fluid reciever">
          <h5 class="text-center">Reciever's information</h5>
          <table class="table">
              <tbody>
                <tr>
                  <td class="text-strong">Name</td>
                  <td>{{order.reciever_name}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Phone</td>
                  <td>{{order.Phone_number}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Address</td>
                  <td>{{order.reciever_address}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Email</td>
                  <td>{{order.reciever_email}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Package description</td>
                  <td>{{order.description}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Weight</td>
                  <td>{{order.weight}}</td>
                </tr>
                <tr>
                  <td class="text-strong">departure date</td>
                  <td>{{order.departure_time}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Arrival date</td>
                  <td>{{order.arrival_time}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Payment method</td>
                  <td>{{order.payment_method}}</td>
                </tr>
                <tr>
                  <td class="text-strong">status</td>
                  <td>{{order.status}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Tracking number</td>
                  <td>{{order.tracking_number}}</td>
                </tr>
              </tbody>
            </table>
      </div>
      <a href="{% url 'AdminSide:update-order' order.id %}"><button type="reset">Update</button></a>
      <a href="{% url 'AdminSide:delete-order' order.id %}"><button type="reset">Delete</button></a>
  </div>

{% endblock %}

adminside/templates/index.html
{%extends 'base.html'%}
{% load static %}
{% block css %}

{% endblock %}
  
{% block content %}
<main id="main" class="main">

  <div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Home</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section dashboard">
    <div class="row">

      <!-- Left side columns -->
      <div class="col-lg-8">
        <div class="row">

          <!-- Sales Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card sales-card">

              <div class="filter">
                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                  <li class="dropdown-header text-start">
                    <h6>Filter</h6>
                  </li>

                  <li><a class="dropdown-item" href="#">Today</a></li>
                  <li><a class="dropdown-item" href="#">This Month</a></li>
                  <li><a class="dropdown-item" href="#">This Year</a></li>
                </ul>
              </div>

              <div class="card-body">
                <h5 class="card-title">New Order <span>| Today</span></h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="bi bi-cart"></i>
                  </div>
                  <div class="ps-3">
                    <h6><a href="{% url 'AdminSide:new-order' %}">Add New Order</a></h6>
                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Sales Card -->

          <!-- Revenue Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card revenue-card">

              <div class="filter">
                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                  <li class="dropdown-header text-start">
                    <h6>Filter</h6>
                  </li>

                  <li><a class="dropdown-item" href="#">Today</a></li>
                  <li><a class="dropdown-item" href="#">This Month</a></li>
                  <li><a class="dropdown-item" href="#">This Year</a></li>
                </ul>
              </div>

              <div class="card-body">
                <h5 class="card-title">Total Orders<span>| This Month</span></h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="bi bi-currency-dollar"></i>
                  </div>
                  <div class="ps-3">
                    <h6>Total Orders</h6>
                   <span class="text-muted small pt-2 ps-1"><a href="{% url 'AdminSide:order-list' %}">view all Orders</a></span>

                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Revenue Card -->

          <!-- Customers Card -->
          <div class="col-xxl-4 col-xl-12">

            <div class="card info-card customers-card">

              <div class="filter">
                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                  <li class="dropdown-header text-start">
                    <h6>Filter</h6>
                  </li>

                  <li><a class="dropdown-item" href="#">Today</a></li>
                  <li><a class="dropdown-item" href="#">This Month</a></li>
                  <li><a class="dropdown-item" href="#">This Year</a></li>
                </ul>
              </div>

              <div class="card-body">
                <h5 class="card-title">Messages <span>| This Year</span></h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="bi bi-people"></i>
                  </div>
                  <div class="ps-3">
                    <h6>Total Messages</h6>
                    <span class="text-danger small pt-1 fw-bold">12%</span> <span class="text-muted small pt-2 ps-1"><a href="{% url 'AdminSide:all-messages' %}">view Messages</a></span>
                    
                  </div>
                </div>

              </div>
            </div>

          </div><!-- End Customers Card -->

          <!-- Reports -->
          <div class="col-12">
            
            <div class="card">

              <div class="filter">
                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                  <li class="dropdown-header text-start">
                    <h6>Filter</h6>
                  </li>

                  <li><a class="dropdown-item" href="#">Today</a></li>
                  <li><a class="dropdown-item" href="#">This Month</a></li>
                  <li><a class="dropdown-item" href="#">This Year</a></li>
                </ul>
              </div>

              <div class="card-body">
                <h5 class="card-title">Reports <span>/Today</span></h5>

                <!-- Line Chart -->
                <div id="reportsChart"></div>

                <script>
                  document.addEventListener("DOMContentLoaded", () => {
                    new ApexCharts(document.querySelector("#reportsChart"), {
                      series: [{
                        name: 'Sales',
                        data: [31, 40, 28, 51, 42, 82, 56],
                      }, {
                        name: 'Revenue',
                        data: [11, 32, 45, 32, 34, 52, 41]
                      }, {
                        name: 'Customers',
                        data: [15, 11, 32, 18, 9, 24, 11]
                      }],
                      chart: {
                        height: 350,
                        type: 'area',
                        toolbar: {
                          show: false
                        },
                      },
                      markers: {
                        size: 4
                      },
                      colors: ['#4154f1', '#2eca6a', '#ff771d'],
                      fill: {
                        type: "gradient",
                        gradient: {
                          shadeIntensity: 1,
                          opacityFrom: 0.3,
                          opacityTo: 0.4,
                          stops: [0, 90, 100]
                        }
                      },
                      dataLabels: {
                        enabled: false
                      },
                      stroke: {
                        curve: 'smooth',
                        width: 2
                      },
                      xaxis: {
                        type: 'datetime',
                        categories: ["2018-09-19T00:00:00.000Z", "2018-09-19T01:30:00.000Z", "2018-09-19T02:30:00.000Z", "2018-09-19T03:30:00.000Z", "2018-09-19T04:30:00.000Z", "2018-09-19T05:30:00.000Z", "2018-09-19T06:30:00.000Z"]
                      },
                      tooltip: {
                        x: {
                          format: 'dd/MM/yy HH:mm'
                        },
                      }
                    }).render();
                  });
                </script>
                <!-- End Line Chart -->

              </div>

            </div>
          </div><!-- End Reports -->

        </div>
      </div><!-- End Left side columns -->
        
      </div><!-- End Right side columns -->

    </div>
  </section>

</main><!-- End #main -->

 {% endblock %} 

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

</html>

adminside/templates/messageDetail.html
{% extends 'base.html '%}
{% load static %}

{% block content %}
<div class="container  shadow p-3 mb-5 rounded">
    <a href="{% url 'AdminSide:all-messages'%}"><button type="button" class="btn-secondary"> << back </button></a>
      <div class="nav navbar border">
          <div class="row">
              <div class="title"><h5><small>Client name: </small>{{ messages.name}}</h5></div>
              
          </div>
      </div>
      <div class="sender">
          <h5 class="text-center">Client information</h5>
          <table class="table">
              <thead>
                <tr>
                  <td class="text-strong">Name</td>
                  <td>{{messages.name}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Email</td>
                  <td>{{messages.email}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Phone</td>
                  <td>{{messages.phone}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Message</td>
                  <td>{{messages.message}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Departure</td>
                  <td>{{messages.departure}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Destination</td>
                  <td>{{messages.departure}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Weight</td>
                  <td>{{messages.weight}}</td>
                </tr>
                <tr>
                  <td class="text-strong">Dimensins</td>
                  <td>{{messages.dimensions}}</td>
                </tr>
              </thead>
            </table>
      </div>
      <a href="{% url 'AdminSide:delete-message' messages.id %}"><button type="reset">Delete</button></a>
  </div>

{% endblock %}

adminside/templates/orderList.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <table class="table table-bordered border-primary">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Client name</th>
            <th scope="col">description</th>
            <th scope="col">status</th>
            <th scope="col">action</th>
          </tr>
        </thead>
        <tbody>
          {% for order in orders %}
          <tr>
            <th >{{forloop.counter}}</th>
            <td>{{order.reciever_name}}</td>
            <td>{{order.description|truncatechars:20}} ...</td>
            <td>{{order.status}}</td>
            <td>
              <a href="{% url 'AdminSide:details' order.id %}"><i class="fa-solid fa-eye"></i>view</a>
              <a href="{% url 'AdminSide:update-order' order.id %}">Edit</a>
              <a href="{% url 'AdminSide:delete-order' order.id %}"><i class="fas fa-trash-alt"></i>delete</a>     
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  
  

{% endblock %}